export const LOAD_MOVIES = 'LOAD_MOVIES';
export const LOAD_ERROR = 'LOAD_ERROR';
export const RESPONSE_PAGE = 'RESPONSE_PAGE';
export const AWAITING_RESPONSE = 'AWAITING_RESPONSE';
export const LOAD_MORE_MOVIES = 'LOAD_MORE_MOVIES';
export const MOVIE_TYPE = 'MOVIE_TYPE';
